# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import imgapp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=imgapp.utils.get_upload_file_path)),
                ('compressed_image', models.ImageField(blank=True, null=True, upload_to=imgapp.utils.get_upload_file_path)),
            ],
        ),
    ]
